name = "positify"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "./workers-site"}

account_id = '<ACCOUNT_ID>'

[build]
command = 'npm run build'

kv_namespaces = [
  { binding = "NAMESPACE_BINDING", id = "<ID>" }
]
