name = "postify"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
compatibility_date = "2021-10-31"
workers_dev = true
site = {bucket = "./build",entry-point = "./workers-site"}

account_id = '42ba4aca6abe337275b912d53b81721d'

kv_namespaces = [
    { binding = "DOCUMENTS_KV", id = "38ecb55eda1b46bcb02e9719c27cf0cd" }
]

[build]
command = 'npm run build'
[build.upload]
format = 'service-worker'

[env.production]
zone_id = "52cd261fce3e52e9691b51211d27c956"

route = "postify.online/*"

kv_namespaces = [
    { binding = "DOCUMENTS_KV", id = "a9b63c8bcceb41b888ee8a92af58e79d" }
]
